### ISSUE TITLE
template.substituteValues is not a function error when performing a push using latest amplify version

### ISSUE THREAD

**Issue by vantablanta** [aws-amplify/amplify-cli#13516]
### How did you install the Amplify CLI?

npm 

### If applicable, what version of Node.js are you using?

v20.10.0

### Amplify CLI Version

12.10.0

### What operating system are you using?

MacOs

### Did you make any manual changes to the cloud resources managed by Amplify? Please describe the changes made.

Just did an amplify push using the latest version of amplify cli.

### Describe the bug

So we noticed this issue a while back when we upgraded the amplify cli version to 12.3.0. At the time we had node v18. We couldn't  perform any push or pull. We always got `template.substituteValues is not a function` and the operation would fail. We rolled back to the  amplify cli version that was initially working  v12.0.3. We've been using this version since.

Checking back now, months later, and it seems issue is still there in the latest version of amplify ?

### Expected behavior

I expected to not get a console error when performing a push locally using the  latest amplify cli version.

### Reproduction steps

Upgrade amplify cli to the latest version. 

Try perform a push. 

### Log output

<details>

```
# Put your logs below this line


```

</details>

### Before submitting, please confirm:

- [X] I have done my best to include a minimal, self-contained set of instructions for consistently reproducing the issue.
- [X] I have removed any sensitive information from my code snippets and submission.

**Comment by ykethan** [comment]
Hey @vantablanta, thank you for reaching out. Could you provide us some additional information on the error message, by running `amplify push` with ` --debug`. 
Does the error occur when running push on a resource such as custom/overrides?
could you run `amplify diagnose --send-report` and provide us the Project Identifier output from the terminal.
