### ISSUE TITLE
toGet.slice(...).join is not a function after update to 4.45.2 

### ISSUE THREAD

**Issue by jncheung** [aws-amplify/amplify-cli#6914]
### Before opening, please confirm:

- [X] I have installed the latest version of the Amplify CLI (see above), and confirmed that the issue still persists.
- [X] I have [searched for duplicate or closed issues](https://github.com/aws-amplify/amplify-cli/issues?q=is%3Aissue+).
- [X] I have read the guide for [submitting bug reports](https://github.com/aws-amplify/amplify-cli/blob/master/CONTRIBUTING.md#bug-reports).
- [X] I have done my best to include a minimal, self-contained set of instructions for consistently reproducing the issue.

### How did you install the Amplify CLI?

npm

### If applicable, what version of Node.js are you using?

12.19.0

### Amplify CLI Version

4.45.2

### What operating system are you using?

mac 10.15.2

### Amplify Categories

Not applicable

### Amplify Commands

push

### Describe the bug

`toGet.slice(...).join is not a function`

### Expected behavior

no error 

### Reproduction steps

I was cloning my `dev` to `sns` using
`amplify env checkout sns` and `amplify push`

### Log output

<details>

```
# Put your logs below this line


```

</details>

![Screenshot 2021-03-19 at 12 16 56 PM](https://user-images.githubusercontent.com/30644696/111731439-72676d80-88ae-11eb-81cc-45c62d77f35d.png)

**Comment by nikhname** [comment]
Which resource is the invalid template tied to? @jncheung

**Comment by kaustavghosh06** [comment]
@jncheung  This issue is a dup of https://github.com/aws-amplify/amplify-cli/issues/6839 and we fixed this in the latest version of the CLI. You'd be able to successfully push and update your stack even with the warning above.

**Comment by jncheung** [comment]
@nikhname it is `auth`, 

and @kaustavghosh06 ,this issue happens in cli version `4.45.2`.

**Comment by ngnathan** [comment]
@kaustavghosh06  I'm also running into issues with this in `4.45.2`, also with my `auth` CFT yml.  

When setting up a new environment and running `amplify push`, the error shows, but after running the push again, it's able to get past the error.

However, in connecting my Github brand to Amplify, I'm unable to get past the error, even when running the Build process again.

Error I get in the "Build" Phase:
```
                                 # Starting phase: build
                                 # Executing command: amplifyPush --simple
2021-03-22T20:22:37.118Z [INFO]: [0mAmplify AppID found:<APPID> Amplify App name is: <NAME>[0m
2021-03-22T20:22:37.171Z [INFO]: [0mBackend environment <ENV> found in Amplify Console app <NAME>: [0m
2021-03-22T20:22:39.024Z [WARNING]: - Fetching updates to backend environment: <ENV> from the cloud.
2021-03-22T20:22:40.143Z [WARNING]: ✔ Successfully pulled backend environment <ENV> from the cloud.
2021-03-22T20:22:40.676Z [INFO]: 
2021-03-22T20:22:42.864Z [INFO]: [33mNote: It is recommended to run this command from the root of your app directory[39m
2021-03-22T20:22:49.744Z [WARNING]: - Initializing your environment: <ENV>
2021-03-22T20:22:51.153Z [WARNING]: ✔ Initialized provider successfully.
2021-03-22T20:22:51.849Z [INFO]: [31mInvalid CloudFormation template: <AUTH YML>[39m
                                 [31mtoGet.slice(...).join is not a function[39m
2021-03-22T20:23:27.060Z [WARNING]: ✖ An error occurred when pushing the resources to the cloud
2021-03-22T20:23:27.079Z [WARNING]: ✖ There was an error initializing your environment.
2021-03-22T20:23:27.138Z [ERROR]: !!! Build failed
2021-03-22T20:23:27.138Z [ERROR]: !!! Non-Zero Exit Code detected
2021-03-22T20:23:27.139Z [INFO]: # Starting environment caching...
2021-03-22T20:23:27.139Z [INFO]: # Environment caching completed
Terminating logging...
```

**Comment by jncheung** [comment]
After I upgraded to `4.46.0`, the issue still exists

here is the log output when i was cloning to a new environment.

![image](https://user-images.githubusercontent.com/30644696/112085473-8e785100-8bc5-11eb-9fce-4c12ef0fd6a2.png)

**Comment by ngnathan** [comment]
@jncheung So I ran `amplify update auth` on an environment that works, selected "Walkthrough all the auth configurations", and went through the entire process again.

When I look at the changes, it seemed to have changed previous `Fn::GetAtt` references to `!GetAtt` and it seems to deploy fine now...

**Comment by jncheung** [comment]
@ngnathan so do i, after successfully cloning to a new environment, the error is gone.

i believe there is a bug living in the creation process. since we both were facing the some error during the `create` process.
