### ISSUE TITLE
src/models/index.d.ts:984:12 - error TS1170: readonly [__modelMeta__]:

### ISSUE THREAD

**Issue by rudyhadoux** [aws-amplify/amplify-cli#12776]
### Amplify CLI Version

12.0.3

### What operating system are you using?

Mac OS Ventura 13.4

### Did you make any manual changes to the cloud resources managed by Amplify? Please describe the changes made.

No.

### Describe the bug

"aws-amplify": "^2.3.0" does not work with Angular.
Error: src/models/index.d.ts:984:12 - error TS1170: A computed property name in a type literal must refer to an expression whose type is a literal type or a 'unique symbol' type.

984   readonly [__modelMeta__]: {

### Expected behavior

AWS Amplify and Angular. Good use together.

### Reproduction steps

ng new app
npm i aws-amplify

### Log output

ng new app
npm i aws-amplify

### Before submitting, please confirm:

- [X] I have done my best to include a minimal, self-contained set of instructions for consistently reproducing the issue.
- [X] I have removed any sensitive information from my code snippets and submission.

**Comment by rudyhadoux** [comment]
It works with aws-amplify 5.1.3.
