### ISSUE TITLE
DataStore fails sync with Validation error of type FieldUndefined: Field 'syncLessons' in type 'Query'

### ISSUE THREAD

**Issue by jonatantibarovsky** [aws-amplify/amplify-cli#12115]
I am getting a sync error after enabling DataStore in my amplify project. This started happening after migrating the api from v1 to v2. 

I've enabled conflict detection in my GraphQL api, set it to auto-merge. 

Here is a screenshoot of the errors. 

<img width="1002" alt="Screenshot 2023-02-27 at 15 41 08" src="https://user-images.githubusercontent.com/33101763/221594802-3f2b89c3-7b44-42ca-b8c4-7796284b7d62.png">

Important to note that none of the models that I have in my schema have a `sync` query generated for it.

There is only one `sync` query generated which is `syncCollectionWorkouts` which is coming from a many-to-many relationship.

`type Collection  
  @model(queries: {get: "getCollectionById", list: "getAllCollections"}) 
  @auth(rules: [
    {allow: private operations: [read]}
  ])
  {
  id: ID! @primaryKey
  name: String
  workouts: [Workout] @manyToMany(relationName: "CollectionWorkouts")
}

type Workout  
  @model(queries: {get: "getWorkoutById", list: "getAllWorkouts"}) 
  {
  id: ID! @primaryKey
  name: String!
  collections: [Collection] @manyToMany(relationName: "CollectionWorkouts")
}
`

**Comment by josefaidt** [comment]
Hey @jonatantibarovsky :wave: would you mind filing this with the bug report template in our API repo? https://github.com/aws-amplify/amplify-category-api/issues/new?assignees=&labels=pending-triage&template=1.bug_report.yaml

This will help us gather additional details around the context of your issue to better diagnose
