### ISSUE TITLE
import * as APITypes from "types" in 12.5.0 breaks the build

### ISSUE THREAD

**Issue by OperationalFallacy** [aws-amplify/amplify-cli#13261]
### How did you install the Amplify CLI?

yarn

### If applicable, what version of Node.js are you using?

v18.17.1

### Amplify CLI Version

12.5.0

### What operating system are you using?

Mac

### Did you make any manual changes to the cloud resources managed by Amplify? Please describe the changes made.

I have pretty advanced configuration where I'm sharing amplify generated graphql resources with Lambda functions, so I can easily use types and methods inside those functions.

The build for Lambda is also customized

### Describe the bug

The builds in 12.4.0 was working fine and 12.5.0 introduce breaking changes with

```
/* tslint:disable */
/* eslint-disable */
// this is an auto generated file. This will be overwritten

import * as APITypes from "types";
type GeneratedQuery<InputType, OutputType> = string & {
  __generatedQueryInput: InputType;
  __generatedQueryOutput: OutputType;
};
```

That import is not working in Node
Cannot find module 'types' or its corresponding type declarations.ts(2307)

### Expected behavior

More standardized imports

### Reproduction steps

amplify codegen

```
yarn amplify:createTrade
yarn run v1.22.19
$ npx projen amplify:createTrade
👾 amplify:createTrade | cd amplify/backend/function/createTrade && rm -rf lib/{amplify,projects} && rm -rf dist && yarn install && tsc -p ./tsconfig.json && tsc-alias -p ./tsconfig.json && cd -
[1/5] 🔍  Validating package.json...
[2/5] 🔍  Resolving packages...
success Already up-to-date.
src/generated/mutations.ts:5:27 - error TS2307: Cannot find module 'types' or its corresponding type declarations.

5 import * as APITypes from "types";
                            ~~~~~~~

src/generated/queries.ts:5:27 - error TS2307: Cannot find module 'types' or its corresponding type declarations.

5 import * as APITypes from "types";
                            ~~~~~~~

src/generated/subscriptions.ts:5:27 - error TS2307: Cannot find module 'types' or its corresponding type declarations.

5 import * as APITypes from "types";
                            ~~~~~~~

Found 3 errors in 3 files.

Errors  Files
     1  src/generated/mutations.ts:5
     1  src/generated/queries.ts:5
     1  src/generated/subscriptions.ts:5
```

Perhaps there is tsconfig option that can enable imports like that? Or perhaps this is a real bug.

### Log output

<details>

```
# Put your logs below this line


```

</details>

### Before submitting, please confirm:

- [X] I have done my best to include a minimal, self-contained set of instructions for consistently reproducing the issue.
- [X] I have removed any sensitive information from my code snippets and submission.

**Comment by pmarkert** [comment]
+1

**Comment by pmarkert** [comment]
I'm running into the same issue since the upgrade. The temporary workaround I found is to simply update the generated queries.ts and mutations.ts to fix the import path.
```
- import * as APITypes from "API";
+ import * as APITypes from "./API";
```

**Comment by develop-matsu** [comment]
I am not sure if this is correct,
As a temporary fix I was able to get it to work by

- Downgrade the version of the local environment
```
npm install -g @aws-amplify/cli@12.4.0 
```

- Temporarily change the settings in amplify.yml.
I was able to get it to work by specifying 12.4.0 as the version when it is automatically built by CI/CD.

```amplify.yml
backend: ```` backend
  phases:: build
    build: phases: build
      commands: npm install -g @
        - npm install -g @aws-amplify/cli@12.4.0
        - amplifyPush --simple
````

**Comment by dpilch** [comment]
Ok, I was able to reproduce with that path. That is unexpected, a custom path like should work. If you change the path to `src/API.ts` that will workaround the issue.
