### ISSUE TITLE
toGet.slice(...).join is not a function after update to 4.45.0

### ISSUE THREAD

**Issue by hisham** [aws-amplify/amplify-cli#6839]
### Before opening, please confirm:

- [X] I have installed the latest version of the Amplify CLI (see above), and confirmed that the issue still persists.
- [X] I have [searched for duplicate or closed issues](https://github.com/aws-amplify/amplify-cli/issues?q=is%3Aissue+).
- [X] I have read the guide for [submitting bug reports](https://github.com/aws-amplify/amplify-cli/blob/master/CONTRIBUTING.md#bug-reports).
- [X] I have done my best to include a minimal, self-contained set of instructions for consistently reproducing the issue.

### How did you install the Amplify CLI?

npm

### If applicable, what version of Node.js are you using?

14.15.3

### Amplify CLI Version

4.45.0

### What operating system are you using?

Mac

### Amplify Categories

auth, storage, function, api

### Amplify Commands

push

### Describe the bug

After upgrade to 4.45.0, running amplify push gives this warning that looks like error but isn't: 

Invalid CloudFormation template: /Users/hisham/.../amplify/backend/auth/..../essapp0f5644a0-cloudformation-template.yml
toGet.slice(...).join is not a function

### Expected behavior

No warnings on amplify push

### Reproduction steps

1. Upgrade to 4.45.0
2. Say Y on the notification to update to node 12
3. Do amplify push

### Log output

```
# Put your logs below this line

```

See the messages at https://github.com/aws-amplify/amplify-cli/issues/5241 for more info.

**Comment by kaustavghosh06** [comment]
We've root-caused the issue and here's the fix for it - https://github.com/aws-amplify/amplify-cli/pull/6834. We're working on getting a release out with the fix for this as we speak.
